version: '3'
services:
  db_dev:
    image: postgres:9.5.5
    restart: always
    environment:
      - POSTGRES_DB=heimdall
      - POSTGRES_USER=heimdall
      - POSTGRES_PASSWORD=heimdall
    expose:
      - '5432'
    ports:
      - '5432:5432'

